CREATE TABLE `auditoria` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tabla` varchar(50) NOT NULL COMMENT 'Nombre de la tabla afectada',
  `registro_id` int(11) NOT NULL COMMENT 'ID del registro afectado',
  `accion` enum('crear','actualizar','eliminar','login','logout') NOT NULL,
  `usuario_id` int(11) DEFAULT NULL,
  `usuario_nombre` varchar(150) DEFAULT NULL COMMENT 'Nombre del usuario (snapshot)',
  `datos_anteriores` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Estado antes del cambio' CHECK (json_valid(`datos_anteriores`)),
  `datos_nuevos` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Estado después del cambio' CHECK (json_valid(`datos_nuevos`)),
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` varchar(500) DEFAULT NULL,
  `descripcion` text DEFAULT NULL COMMENT 'Descripción legible de la acción',
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `auditoria_tabla_registro_id` (`tabla`,`registro_id`),
  KEY `auditoria_usuario_id` (`usuario_id`),
  KEY `auditoria_accion` (`accion`),
  KEY `auditoria_created_at` (`created_at`),
  CONSTRAINT `auditoria_ibfk_1` FOREIGN KEY (`usuario_id`) REFERENCES `usuarios` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `backup_registros` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `fecha` datetime NOT NULL,
  `archivo` varchar(255) DEFAULT NULL COMMENT 'Nombre del archivo generado (ej: istho_crm_backup_2026-04-01.sql.gz)',
  `tamano_bytes` bigint(20) DEFAULT NULL COMMENT 'Tamaño del archivo comprimido en bytes',
  `estado` enum('exitoso','fallido') NOT NULL DEFAULT 'exitoso',
  `duracion_segundos` int(11) DEFAULT NULL COMMENT 'Tiempo que tardó el proceso de backup',
  `error_mensaje` text DEFAULT NULL COMMENT 'Mensaje de error si el backup falló',
  `origen` enum('automatico','manual') NOT NULL DEFAULT 'automatico' COMMENT 'Automático (cron diario) o Manual (disparado por admin)',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `backup_registros_fecha` (`fecha`),
  KEY `backup_registros_estado` (`estado`),
  KEY `backup_registros_origen` (`origen`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `caja_inventario` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `inventario_id` int(11) NOT NULL COMMENT 'Referencia al producto maestro (Inventario)',
  `operacion_id` int(11) DEFAULT NULL COMMENT 'Operación de entrada o salida',
  `operacion_detalle_id` int(11) DEFAULT NULL COMMENT 'Línea específica de la operación',
  `numero_caja` varchar(50) DEFAULT NULL COMMENT 'Número de caja del WMS (ej: 12345)',
  `lote` varchar(50) DEFAULT NULL COMMENT 'Número de lote (ej: 20260309)',
  `ubicacion` varchar(50) DEFAULT NULL COMMENT 'Ubicación física en bodega (ej: A1-B2-C3)',
  `cantidad` decimal(15,3) NOT NULL DEFAULT 0.000 COMMENT 'Cantidad de unidades en esta caja',
  `peso` decimal(15,4) DEFAULT NULL COMMENT 'Peso en KG',
  `unidad_medida` varchar(20) DEFAULT 'UND' COMMENT 'UND, KG, LT, CAJ, etc.',
  `tipo` enum('entrada','salida','kardex') NOT NULL COMMENT 'Si la caja ingresó, salió o fue ajustada por kardex',
  `estado` enum('disponible','despachada','en_transito','dañada','devuelta','inactiva') DEFAULT 'disponible' COMMENT 'Estado actual de la caja',
  `documento_asociado` varchar(100) DEFAULT NULL COMMENT 'Documento/pedido asociado (ej: KDC9059)',
  `lote_externo` varchar(50) DEFAULT NULL COMMENT 'Lote externo del WMS',
  `fecha_vencimiento` date DEFAULT NULL,
  `fecha_movimiento` datetime DEFAULT NULL COMMENT 'Fecha en que se registró el movimiento',
  `observaciones` text DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `caja_inventario_inventario_id` (`inventario_id`),
  KEY `caja_inventario_operacion_id` (`operacion_id`),
  KEY `caja_inventario_operacion_detalle_id` (`operacion_detalle_id`),
  KEY `caja_inventario_numero_caja` (`numero_caja`),
  KEY `caja_inventario_lote` (`lote`),
  KEY `caja_inventario_tipo` (`tipo`),
  KEY `caja_inventario_estado` (`estado`),
  KEY `caja_inventario_ubicacion` (`ubicacion`),
  KEY `idx_caja_inv_tipo_estado` (`inventario_id`,`tipo`,`estado`),
  CONSTRAINT `caja_inventario_ibfk_1` FOREIGN KEY (`inventario_id`) REFERENCES `inventario` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `caja_inventario_ibfk_2` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `caja_inventario_ibfk_3` FOREIGN KEY (`operacion_detalle_id`) REFERENCES `operacion_detalle` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `cajas_menores` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `numero` varchar(20) NOT NULL COMMENT 'Número de caja menor (CM-XXXX)',
  `asignado_a` int(11) NOT NULL COMMENT 'Usuario asignado a la caja',
  `creado_por` int(11) NOT NULL COMMENT 'Usuario que creó la caja (financiera/admin)',
  `saldo_inicial` decimal(12,2) NOT NULL DEFAULT 0.00,
  `saldo_actual` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT 'Saldo calculado: inicial + ingresos - egresos aprobados',
  `total_ingresos` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total_egresos` decimal(12,2) NOT NULL DEFAULT 0.00,
  `estado` enum('abierta','en_revision','cerrada') NOT NULL DEFAULT 'abierta',
  `fecha_apertura` date NOT NULL,
  `fecha_cierre` date DEFAULT NULL,
  `caja_anterior_id` int(11) DEFAULT NULL COMMENT 'Caja de la cual se trasladó el sobrante',
  `saldo_trasladado` decimal(12,2) DEFAULT 0.00 COMMENT 'Monto heredado de caja anterior',
  `observaciones` text DEFAULT NULL,
  `observaciones_cierre` text DEFAULT NULL,
  `cerrada_por` int(11) DEFAULT NULL COMMENT 'Usuario que cerró la caja',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `cajas_menores_numero` (`numero`),
  KEY `cerrada_por` (`cerrada_por`),
  KEY `cajas_menores_asignado_a` (`asignado_a`),
  KEY `cajas_menores_estado` (`estado`),
  KEY `cajas_menores_creado_por` (`creado_por`),
  KEY `cajas_menores_fecha_apertura` (`fecha_apertura`),
  KEY `cajas_menores_caja_anterior_id` (`caja_anterior_id`),
  CONSTRAINT `cajas_menores_ibfk_1` FOREIGN KEY (`asignado_a`) REFERENCES `usuarios` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT `cajas_menores_ibfk_2` FOREIGN KEY (`creado_por`) REFERENCES `usuarios` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT `cajas_menores_ibfk_3` FOREIGN KEY (`caja_anterior_id`) REFERENCES `cajas_menores` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `cajas_menores_ibfk_4` FOREIGN KEY (`cerrada_por`) REFERENCES `usuarios` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `clientes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `codigo_cliente` varchar(20) NOT NULL,
  `razon_social` varchar(200) NOT NULL,
  `nit` varchar(20) NOT NULL,
  `direccion` varchar(255) DEFAULT NULL,
  `ciudad` varchar(100) DEFAULT NULL,
  `departamento` varchar(100) DEFAULT NULL,
  `telefono` varchar(50) DEFAULT NULL,
  `email` varchar(150) DEFAULT NULL,
  `sitio_web` varchar(200) DEFAULT NULL,
  `tipo_cliente` enum('corporativo','pyme','persona_natural') DEFAULT 'corporativo',
  `sector` varchar(100) DEFAULT NULL COMMENT 'Sector económico: Alimentos, Retail, Industrial, etc.',
  `estado` enum('activo','inactivo','suspendido') DEFAULT 'activo',
  `fecha_inicio_relacion` date DEFAULT NULL,
  `notas` text DEFAULT NULL,
  `logo_url` varchar(500) DEFAULT NULL COMMENT 'URL del logo del cliente',
  `ultima_sincronizacion_wms` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `clientes_codigo_cliente_unique` (`codigo_cliente`),
  UNIQUE KEY `clientes_nit_unique` (`nit`),
  KEY `clientes_codigo_cliente` (`codigo_cliente`),
  KEY `clientes_nit` (`nit`),
  KEY `clientes_razon_social` (`razon_social`),
  KEY `clientes_estado` (`estado`),
  KEY `clientes_tipo_cliente` (`tipo_cliente`),
  KEY `clientes_ciudad` (`ciudad`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `configuracion_wms` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `categoria` enum('motivo_kardex','tipo_orden','estado_valido') NOT NULL COMMENT 'Categoría: motivo_kardex, tipo_orden, estado_valido',
  `valor_wms` varchar(100) NOT NULL COMMENT 'Valor exacto que envía el WMS (ej: "Recarga", "Recepcion", "Finalizada")',
  `valor_crm` varchar(100) NOT NULL COMMENT 'Nombre que se muestra en el CRM (ej: "Recarga de stock", "CO", "Finalizada")',
  `tipo_documento` enum('CO','PK','CR') DEFAULT NULL COMMENT 'Solo para tipo_orden: CO=Entrada, PK=Salida, CR=Kardex',
  `requiere_detalle` tinyint(1) DEFAULT 0 COMMENT 'Si true, el WMS envía un campo adicional con el detalle del motivo',
  `descripcion` varchar(255) DEFAULT NULL COMMENT 'Descripción para el admin',
  `orden` int(11) DEFAULT 0 COMMENT 'Orden de visualización en el panel',
  `activo` tinyint(1) DEFAULT 1,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `configuracion_wms_categoria_valor_wms` (`categoria`,`valor_wms`),
  KEY `configuracion_wms_categoria_activo` (`categoria`,`activo`),
  KEY `configuracion_wms_activo` (`activo`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `contactos` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cliente_id` int(11) NOT NULL,
  `nombre` varchar(150) NOT NULL,
  `cargo` varchar(100) DEFAULT NULL,
  `telefono` varchar(50) DEFAULT NULL,
  `celular` varchar(50) DEFAULT NULL,
  `email` varchar(150) DEFAULT NULL,
  `es_principal` tinyint(1) DEFAULT 0 COMMENT 'Indica si es el contacto principal del cliente',
  `recibe_notificaciones` tinyint(1) DEFAULT 1 COMMENT 'Indica si recibe emails de notificación',
  `tipos_notificacion` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Tipos de notificación: [''todas''] o combinación de [''ingreso'',''salida'',''kardex'']' CHECK (json_valid(`tipos_notificacion`)),
  `notas` text DEFAULT NULL,
  `activo` tinyint(1) DEFAULT 1,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `contactos_cliente_id` (`cliente_id`),
  KEY `contactos_email` (`email`),
  KEY `contactos_es_principal` (`es_principal`),
  KEY `contactos_cliente_id_es_principal` (`cliente_id`,`es_principal`),
  KEY `contactos_cliente_id_activo` (`cliente_id`,`activo`),
  CONSTRAINT `contactos_ibfk_1` FOREIGN KEY (`cliente_id`) REFERENCES `clientes` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `inventario` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cliente_id` int(11) NOT NULL,
  `sku` varchar(50) NOT NULL COMMENT 'Código único del producto',
  `codigo_barras` varchar(50) DEFAULT NULL COMMENT 'Código de barras EAN/UPC',
  `producto` varchar(200) NOT NULL,
  `descripcion` text DEFAULT NULL,
  `categoria` varchar(100) DEFAULT NULL COMMENT 'Categoría del producto',
  `unidad_medida` varchar(20) DEFAULT 'UND' COMMENT 'UND, KG, LT, CAJ, PAQ, etc.',
  `cantidad` decimal(15,3) NOT NULL DEFAULT 0.000,
  `stock_minimo` decimal(15,3) DEFAULT 0.000 COMMENT 'Cantidad mínima para alertas de stock bajo',
  `stock_maximo` decimal(15,3) DEFAULT NULL COMMENT 'Cantidad máxima recomendada',
  `fecha_vencimiento` date DEFAULT NULL,
  `fecha_ingreso` date DEFAULT NULL,
  `costo_unitario` decimal(15,2) DEFAULT NULL COMMENT 'Costo unitario en COP',
  `estado` enum('disponible','reservado','dañado','cuarentena','vencido') DEFAULT 'disponible',
  `codigo_wms` varchar(50) DEFAULT NULL COMMENT 'Código del producto en WMS Centhrix',
  `ultima_sincronizacion_wms` datetime DEFAULT NULL,
  `notas` text DEFAULT NULL,
  `alertas_silenciadas` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Tipos de alerta silenciados: { "agotado": "2026-03-11", "bajo_stock": "2026-03-11" }' CHECK (json_valid(`alertas_silenciadas`)),
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_cliente_sku` (`cliente_id`,`sku`),
  KEY `inventario_cliente_id` (`cliente_id`),
  KEY `inventario_sku` (`sku`),
  KEY `inventario_codigo_barras` (`codigo_barras`),
  KEY `inventario_producto` (`producto`),
  KEY `inventario_estado` (`estado`),
  KEY `inventario_fecha_vencimiento` (`fecha_vencimiento`),
  CONSTRAINT `inventario_ibfk_1` FOREIGN KEY (`cliente_id`) REFERENCES `clientes` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `movimientos_caja_menor` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `consecutivo` int(11) NOT NULL COMMENT 'Consecutivo global de movimientos',
  `caja_menor_id` int(11) NOT NULL,
  `viaje_id` int(11) DEFAULT NULL COMMENT 'Viaje asociado (null si es movimiento directo)',
  `tipo_movimiento` enum('ingreso','egreso') NOT NULL,
  `concepto` varchar(50) NOT NULL,
  `concepto_otro` varchar(100) DEFAULT NULL COMMENT 'Descripción cuando concepto = otros',
  `valor` decimal(12,2) NOT NULL,
  `aprobado` tinyint(1) DEFAULT 0,
  `valor_aprobado` decimal(12,2) DEFAULT NULL COMMENT 'Valor aprobado por financiera (puede diferir del valor original)',
  `aprobado_por` int(11) DEFAULT NULL COMMENT 'Usuario que aprobó/rechazó el movimiento',
  `fecha_aprobacion` datetime DEFAULT NULL,
  `rechazado` tinyint(1) DEFAULT 0,
  `observaciones_aprobacion` text DEFAULT NULL,
  `descripcion` text DEFAULT NULL,
  `soporte_url` mediumtext DEFAULT NULL COMMENT 'Soporte como data URI base64 o ruta de archivo',
  `soporte_nombre` varchar(255) DEFAULT NULL COMMENT 'Nombre original del archivo de soporte',
  `usuario_id` int(11) NOT NULL COMMENT 'Usuario asociado al movimiento',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `movimientos_caja_menor_consecutivo` (`consecutivo`),
  KEY `aprobado_por` (`aprobado_por`),
  KEY `movimientos_caja_menor_caja_menor_id` (`caja_menor_id`),
  KEY `movimientos_caja_menor_viaje_id` (`viaje_id`),
  KEY `movimientos_caja_menor_tipo_movimiento` (`tipo_movimiento`),
  KEY `movimientos_caja_menor_concepto` (`concepto`),
  KEY `movimientos_caja_menor_aprobado` (`aprobado`),
  KEY `movimientos_caja_menor_usuario_id` (`usuario_id`),
  KEY `movimientos_caja_menor_caja_menor_id_tipo_movimiento` (`caja_menor_id`,`tipo_movimiento`),
  KEY `movimientos_caja_menor_aprobado_rechazado` (`aprobado`,`rechazado`),
  KEY `movimientos_caja_menor_caja_menor_id_aprobado` (`caja_menor_id`,`aprobado`),
  CONSTRAINT `movimientos_caja_menor_ibfk_1` FOREIGN KEY (`caja_menor_id`) REFERENCES `cajas_menores` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `movimientos_caja_menor_ibfk_2` FOREIGN KEY (`viaje_id`) REFERENCES `viajes` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `movimientos_caja_menor_ibfk_3` FOREIGN KEY (`aprobado_por`) REFERENCES `usuarios` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `movimientos_caja_menor_ibfk_4` FOREIGN KEY (`usuario_id`) REFERENCES `usuarios` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `movimientos_inventario` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `inventario_id` int(11) NOT NULL COMMENT 'Producto afectado por el movimiento',
  `usuario_id` int(11) DEFAULT NULL COMMENT 'Usuario que realizó el movimiento',
  `operacion_id` int(11) DEFAULT NULL COMMENT 'Operación de ingreso/salida relacionada',
  `tipo` enum('entrada','salida','ajuste','reserva','liberacion','transferencia') NOT NULL COMMENT 'Tipo de movimiento',
  `motivo` varchar(255) DEFAULT NULL COMMENT 'Razón del movimiento (Compra, Venta, Ajuste, etc.)',
  `cantidad` decimal(15,3) NOT NULL COMMENT 'Cantidad movida (+ entrada, - salida)',
  `stock_anterior` decimal(15,3) NOT NULL COMMENT 'Stock antes del movimiento',
  `stock_resultante` decimal(15,3) NOT NULL COMMENT 'Stock después del movimiento',
  `documento_referencia` varchar(100) DEFAULT NULL COMMENT 'Factura, OC, remisión, etc.',
  `observaciones` text DEFAULT NULL COMMENT 'Notas adicionales',
  `ubicacion_origen` varchar(100) DEFAULT NULL COMMENT 'Ubicación de origen',
  `ubicacion_destino` varchar(100) DEFAULT NULL COMMENT 'Ubicación de destino',
  `costo_unitario` decimal(15,2) DEFAULT NULL COMMENT 'Costo unitario al momento del movimiento',
  `fecha_movimiento` datetime NOT NULL COMMENT 'Fecha y hora del movimiento',
  `ip_address` varchar(45) DEFAULT NULL COMMENT 'IP desde donde se realizó',
  PRIMARY KEY (`id`),
  KEY `movimientos_inventario_inventario_id` (`inventario_id`),
  KEY `movimientos_inventario_usuario_id` (`usuario_id`),
  KEY `movimientos_inventario_operacion_id` (`operacion_id`),
  KEY `movimientos_inventario_fecha_movimiento` (`fecha_movimiento`),
  KEY `movimientos_inventario_tipo` (`tipo`),
  KEY `movimientos_inventario_documento_referencia` (`documento_referencia`),
  KEY `idx_inventario_fecha` (`inventario_id`,`fecha_movimiento`),
  CONSTRAINT `movimientos_inventario_ibfk_1` FOREIGN KEY (`inventario_id`) REFERENCES `inventario` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `movimientos_inventario_ibfk_2` FOREIGN KEY (`usuario_id`) REFERENCES `usuarios` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `movimientos_inventario_ibfk_3` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Historial de movimientos de inventario - Trazabilidad ISO 9001';

CREATE TABLE `notificaciones` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `usuario_id` int(11) NOT NULL COMMENT 'Usuario destinatario',
  `tipo` enum('despacho','alerta','cliente','reporte','sistema','inventario') NOT NULL DEFAULT 'sistema' COMMENT 'Tipo de notificación',
  `titulo` varchar(255) NOT NULL COMMENT 'Título de la notificación',
  `mensaje` text NOT NULL COMMENT 'Contenido del mensaje',
  `prioridad` enum('baja','normal','alta','urgente') NOT NULL DEFAULT 'normal' COMMENT 'Nivel de prioridad',
  `leida` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Si fue leída',
  `fecha_lectura` datetime DEFAULT NULL COMMENT 'Cuándo se leyó',
  `accion_url` varchar(255) DEFAULT NULL COMMENT 'URL de acción relacionada',
  `accion_label` varchar(100) DEFAULT NULL COMMENT 'Texto del botón de acción',
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Datos adicionales en JSON' CHECK (json_valid(`metadata`)),
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `notificaciones_usuario_id` (`usuario_id`),
  KEY `notificaciones_tipo` (`tipo`),
  KEY `notificaciones_leida` (`leida`),
  KEY `notificaciones_prioridad` (`prioridad`),
  KEY `notificaciones_created_at` (`created_at`),
  KEY `idx_usuario_leida` (`usuario_id`,`leida`),
  CONSTRAINT `notificaciones_ibfk_1` FOREIGN KEY (`usuario_id`) REFERENCES `usuarios` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Notificaciones del sistema CRM ISTHO';

CREATE TABLE `notificaciones_email` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `para` text NOT NULL COMMENT 'Correos destinatarios separados por coma',
  `cc` text DEFAULT NULL,
  `cco` text DEFAULT NULL,
  `asunto` varchar(255) NOT NULL,
  `cuerpo_html` longtext NOT NULL,
  `cuerpo_texto` text DEFAULT NULL COMMENT 'Versión texto plano',
  `adjuntos` text DEFAULT NULL,
  `tipo` enum('operacion_cierre','alerta_inventario','bienvenida','recuperacion_password','general') DEFAULT 'general',
  `referencia_tipo` varchar(50) DEFAULT NULL COMMENT 'Ej: operacion, cliente, usuario',
  `referencia_id` int(11) DEFAULT NULL,
  `estado` enum('pendiente','enviado','fallido','cancelado') DEFAULT 'pendiente',
  `intentos` int(11) DEFAULT 0,
  `max_intentos` int(11) DEFAULT 3,
  `fecha_programada` datetime DEFAULT NULL COMMENT 'Para envíos programados',
  `fecha_envio` datetime DEFAULT NULL,
  `mensaje_id` varchar(255) DEFAULT NULL COMMENT 'Message-ID del servidor SMTP',
  `error` text DEFAULT NULL COMMENT 'Mensaje de error si falló',
  `metadata` text DEFAULT NULL,
  `creado_por` int(11) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `notificaciones_email_estado` (`estado`),
  KEY `notificaciones_email_tipo` (`tipo`),
  KEY `notificaciones_email_referencia_tipo_referencia_id` (`referencia_tipo`,`referencia_id`),
  KEY `notificaciones_email_fecha_programada` (`fecha_programada`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `operacion_averias` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `operacion_id` int(11) NOT NULL,
  `detalle_id` int(11) DEFAULT NULL COMMENT 'Referencia al detalle/producto específico',
  `sku` varchar(50) NOT NULL COMMENT 'SKU del producto con avería',
  `cantidad` decimal(15,3) NOT NULL COMMENT 'Cantidad de unidades averiadas',
  `tipo_averia` varchar(100) DEFAULT NULL COMMENT 'Tipo: golpeado, mojado, roto, vencido, etc.',
  `descripcion` text DEFAULT NULL,
  `foto_url` varchar(500) DEFAULT NULL COMMENT 'Ruta de la foto de evidencia',
  `foto_nombre` varchar(255) DEFAULT NULL,
  `foto_tipo` varchar(50) DEFAULT NULL COMMENT 'MIME type de la imagen',
  `foto_tamanio` int(11) DEFAULT NULL COMMENT 'Tamaño en bytes',
  `cloudinary_public_id` varchar(500) DEFAULT NULL COMMENT 'Public ID en Cloudinary para eliminación',
  `cantidad_afectada` int(11) DEFAULT NULL COMMENT 'Número de unidades afectadas por la avería',
  `registrado_por` int(11) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `registrado_por` (`registrado_por`),
  KEY `operacion_averias_operacion_id` (`operacion_id`),
  KEY `operacion_averias_detalle_id` (`detalle_id`),
  KEY `operacion_averias_sku` (`sku`),
  CONSTRAINT `operacion_averias_ibfk_1` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `operacion_averias_ibfk_2` FOREIGN KEY (`detalle_id`) REFERENCES `operacion_detalle` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `operacion_averias_ibfk_3` FOREIGN KEY (`registrado_por`) REFERENCES `usuarios` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `operacion_detalle` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `operacion_id` int(11) NOT NULL,
  `inventario_id` int(11) DEFAULT NULL COMMENT 'Referencia al registro de inventario (para gestión de stock)',
  `sku` varchar(50) NOT NULL,
  `producto` varchar(200) NOT NULL,
  `cantidad` decimal(15,3) NOT NULL,
  `unidad_medida` varchar(20) DEFAULT 'UND',
  `lote` varchar(50) DEFAULT NULL,
  `fecha_vencimiento` date DEFAULT NULL,
  `cantidad_averia` decimal(15,3) DEFAULT 0.000 COMMENT 'Cantidad de unidades con avería',
  `tipo_averia` varchar(100) DEFAULT NULL COMMENT 'Tipo de avería: golpeado, mojado, vencido, etc.',
  `observaciones_averia` text DEFAULT NULL,
  `numero_caja` varchar(50) DEFAULT NULL COMMENT 'Número de caja del WMS (un producto puede tener múltiples cajas)',
  `lote_externo` varchar(50) DEFAULT NULL COMMENT 'Lote externo del WMS (lote campo existente = lote interno)',
  `documento_asociado` varchar(100) DEFAULT NULL COMMENT 'Documento/pedido asociado a esta línea (ej: KDC9059)',
  `peso` decimal(15,4) DEFAULT NULL COMMENT 'Peso del producto en KG',
  `verificado` tinyint(1) DEFAULT 0 COMMENT 'Indica si la línea ha sido verificada en la auditoría',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `operacion_detalle_operacion_id` (`operacion_id`),
  KEY `operacion_detalle_sku` (`sku`),
  KEY `operacion_detalle_inventario_id` (`inventario_id`),
  CONSTRAINT `operacion_detalle_ibfk_1` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `operacion_detalle_ibfk_2` FOREIGN KEY (`inventario_id`) REFERENCES `inventario` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `operacion_documentos` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `operacion_id` int(11) NOT NULL,
  `tipo_documento` enum('cumplido','factura','remision','acta_entrega','documento_importacion','otro') DEFAULT 'cumplido',
  `nombre` varchar(255) NOT NULL COMMENT 'Nombre descriptivo del documento',
  `archivo_url` varchar(500) NOT NULL COMMENT 'Ruta del archivo',
  `archivo_nombre` varchar(255) NOT NULL COMMENT 'Nombre original del archivo',
  `archivo_tipo` varchar(100) DEFAULT NULL COMMENT 'MIME type',
  `archivo_tamanio` int(11) DEFAULT NULL COMMENT 'Tamaño en bytes',
  `descripcion` text DEFAULT NULL,
  `cloudinary_public_id` varchar(500) DEFAULT NULL COMMENT 'Public ID en Cloudinary para eliminación',
  `subido_por` int(11) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `subido_por` (`subido_por`),
  KEY `operacion_documentos_operacion_id` (`operacion_id`),
  KEY `operacion_documentos_tipo_documento` (`tipo_documento`),
  CONSTRAINT `operacion_documentos_ibfk_1` FOREIGN KEY (`operacion_id`) REFERENCES `operaciones` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `operacion_documentos_ibfk_2` FOREIGN KEY (`subido_por`) REFERENCES `usuarios` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `operaciones` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `numero_operacion` varchar(20) NOT NULL COMMENT 'Número interno CRM (ej: OP-2026-0001)',
  `tipo` enum('ingreso','salida','kardex') NOT NULL,
  `documento_wms` varchar(50) DEFAULT NULL COMMENT 'Número de documento en el WMS (opcional para modo manual)',
  `cliente_id` int(11) NOT NULL,
  `fecha_documento` date DEFAULT NULL COMMENT 'Fecha del documento WMS',
  `fecha_operacion` date NOT NULL COMMENT 'Fecha de la operación en CRM',
  `fecha_cierre` datetime DEFAULT NULL COMMENT 'Fecha y hora de cierre de la operación',
  `origen` varchar(200) DEFAULT NULL,
  `destino` varchar(200) DEFAULT NULL,
  `vehiculo_placa` varchar(10) DEFAULT NULL,
  `vehiculo_tipo` varchar(50) DEFAULT NULL COMMENT 'Tipo de vehículo (Furgón, Turbo, Tractomula, etc.)',
  `conductor_nombre` varchar(150) DEFAULT NULL,
  `conductor_cedula` varchar(20) DEFAULT NULL,
  `conductor_telefono` varchar(50) DEFAULT NULL,
  `total_referencias` int(11) DEFAULT 0 COMMENT 'Total de SKUs/referencias',
  `total_unidades` decimal(15,3) DEFAULT 0.000 COMMENT 'Total de unidades',
  `total_averias` int(11) DEFAULT 0 COMMENT 'Total de unidades con avería',
  `prioridad` enum('baja','normal','alta','urgente') DEFAULT 'normal' COMMENT 'Prioridad de la operación',
  `estado` enum('pendiente','en_proceso','cerrado','anulado') DEFAULT 'pendiente',
  `correo_enviado` tinyint(1) DEFAULT 0,
  `fecha_correo_enviado` datetime DEFAULT NULL,
  `correos_destino` text DEFAULT NULL COMMENT 'Lista de correos separados por coma',
  `observaciones` text DEFAULT NULL,
  `observaciones_cierre` text DEFAULT NULL,
  `creado_por` int(11) DEFAULT NULL,
  `cerrado_por` int(11) DEFAULT NULL,
  `numero_picking` varchar(50) DEFAULT NULL COMMENT 'Número de picking del WMS (para salidas)',
  `tipo_documento_wms` enum('CO','PK','CR') DEFAULT NULL COMMENT 'Tipo de documento WMS: CO=Recepción, PK=Picking, CR=Kardex',
  `motivo_kardex` varchar(255) DEFAULT NULL COMMENT 'Motivo del ajuste Kardex (lista predefinida o texto libre)',
  `sucursal_entrega` varchar(200) DEFAULT NULL COMMENT 'Sucursal de entrega del WMS',
  `ciudad_destino` varchar(100) DEFAULT NULL COMMENT 'Ciudad de destino del WMS',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `operaciones_numero_operacion` (`numero_operacion`),
  KEY `creado_por` (`creado_por`),
  KEY `cerrado_por` (`cerrado_por`),
  KEY `operaciones_documento_wms` (`documento_wms`),
  KEY `operaciones_cliente_id` (`cliente_id`),
  KEY `operaciones_tipo` (`tipo`),
  KEY `operaciones_estado` (`estado`),
  KEY `operaciones_fecha_operacion` (`fecha_operacion`),
  KEY `operaciones_prioridad` (`prioridad`),
  KEY `operaciones_tipo_documento_wms` (`tipo_documento_wms`),
  KEY `operaciones_tipo_estado` (`tipo`,`estado`),
  KEY `operaciones_tipo_cliente_id` (`tipo`,`cliente_id`),
  KEY `operaciones_tipo_created_at` (`tipo`,`created_at`),
  KEY `operaciones_tipo_estado_fecha_operacion` (`tipo`,`estado`,`fecha_operacion`),
  KEY `operaciones_tipo_cliente_id_estado` (`tipo`,`cliente_id`,`estado`),
  KEY `operaciones_cliente_id_estado` (`cliente_id`,`estado`),
  CONSTRAINT `operaciones_ibfk_1` FOREIGN KEY (`cliente_id`) REFERENCES `clientes` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `operaciones_ibfk_2` FOREIGN KEY (`creado_por`) REFERENCES `usuarios` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `operaciones_ibfk_3` FOREIGN KEY (`cerrado_por`) REFERENCES `usuarios` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `password_historico` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `usuario_id` int(11) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `usuario_id` (`usuario_id`),
  CONSTRAINT `password_historico_ibfk_1` FOREIGN KEY (`usuario_id`) REFERENCES `usuarios` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `permisos` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `modulo` varchar(30) NOT NULL COMMENT 'Nombre del módulo (dashboard, clientes, inventario, etc.)',
  `accion` varchar(30) NOT NULL COMMENT 'Acción dentro del módulo (ver, crear, editar, eliminar, etc.)',
  `descripcion` varchar(255) DEFAULT NULL COMMENT 'Descripción legible del permiso',
  `grupo` varchar(50) DEFAULT NULL COMMENT 'Grupo para organizar en la UI (ej: Operaciones, Gestión, Sistema)',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `permisos_modulo_accion` (`modulo`,`accion`),
  KEY `permisos_modulo` (`modulo`),
  KEY `permisos_grupo` (`grupo`)
) ENGINE=InnoDB AUTO_INCREMENT=68 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `plantillas_email` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(150) NOT NULL COMMENT 'Nombre interno de la plantilla',
  `tipo` enum('operacion_cierre','alerta_inventario','bienvenida','general') NOT NULL DEFAULT 'general' COMMENT 'Tipo de evento al que aplica la plantilla',
  `subtipo` varchar(50) DEFAULT NULL COMMENT 'Subtipo para diferenciar plantillas del mismo tipo (ej: ingreso, salida)',
  `asunto_template` varchar(255) NOT NULL COMMENT 'Asunto del correo (acepta variables Handlebars)',
  `cuerpo_html` longtext NOT NULL COMMENT 'Cuerpo HTML de la plantilla (acepta variables Handlebars)',
  `firma_habilitada` tinyint(1) DEFAULT 1 COMMENT 'Si incluye la firma de ISTHO al final',
  `firma_html` text DEFAULT NULL COMMENT 'Firma HTML personalizada (si es null se usa la firma por defecto)',
  `campos_disponibles` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Lista de campos/variables disponibles para esta plantilla' CHECK (json_valid(`campos_disponibles`)),
  `es_predeterminada` tinyint(1) DEFAULT 0 COMMENT 'Si es la plantilla por defecto para su tipo',
  `activo` tinyint(1) DEFAULT 1,
  `creado_por` int(11) DEFAULT NULL,
  `actualizado_por` int(11) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `reportes_programados` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(100) NOT NULL COMMENT 'Nombre descriptivo del reporte',
  `tipo_reporte` enum('operaciones','inventario','clientes','viajes','cajas_menores','gastos') NOT NULL,
  `formato` enum('excel','pdf','ambos') DEFAULT 'excel',
  `cron_expresion` varchar(50) NOT NULL COMMENT 'Expresión cron para programación',
  `frecuencia_label` varchar(100) DEFAULT NULL COMMENT 'Descripción legible (ej: Cada lunes a las 8:00 AM)',
  `destinatarios` text NOT NULL COMMENT 'Emails separados por coma',
  `cliente_id` int(11) DEFAULT NULL,
  `filtros` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Filtros adicionales (estado, tipo, etc.)' CHECK (json_valid(`filtros`)),
  `activo` tinyint(1) DEFAULT 1,
  `creado_por` int(11) DEFAULT NULL,
  `ultima_ejecucion` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `cliente_id` (`cliente_id`),
  KEY `reportes_programados_activo` (`activo`),
  KEY `reportes_programados_tipo_reporte` (`tipo_reporte`),
  KEY `reportes_programados_creado_por` (`creado_por`),
  CONSTRAINT `reportes_programados_ibfk_1` FOREIGN KEY (`cliente_id`) REFERENCES `clientes` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `reportes_programados_ibfk_2` FOREIGN KEY (`creado_por`) REFERENCES `usuarios` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `rol_permisos` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `rol_id` int(11) NOT NULL,
  `permiso_id` int(11) NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `rol_permisos_permiso_id_rol_id_unique` (`rol_id`,`permiso_id`),
  UNIQUE KEY `rol_permisos_rol_id_permiso_id` (`rol_id`,`permiso_id`),
  KEY `rol_permisos_rol_id` (`rol_id`),
  KEY `rol_permisos_permiso_id` (`permiso_id`),
  CONSTRAINT `rol_permisos_ibfk_10` FOREIGN KEY (`permiso_id`) REFERENCES `permisos` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `rol_permisos_ibfk_9` FOREIGN KEY (`rol_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=741 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `roles` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(50) NOT NULL,
  `codigo` varchar(30) NOT NULL,
  `descripcion` varchar(255) DEFAULT NULL,
  `nivel_jerarquia` int(11) NOT NULL DEFAULT 50 COMMENT 'Mayor número = más permisos. Usado para requiereRolMinimo()',
  `es_sistema` tinyint(1) DEFAULT 0 COMMENT 'Roles del sistema no se pueden eliminar ni cambiar su código',
  `es_cliente` tinyint(1) DEFAULT 0 COMMENT 'Indica si es un rol de portal cliente',
  `color` varchar(7) DEFAULT '#6B7280' COMMENT 'Color hex para badges en la UI',
  `activo` tinyint(1) DEFAULT 1,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `roles_nombre_unique` (`nombre`),
  UNIQUE KEY `roles_codigo` (`codigo`),
  KEY `roles_activo` (`activo`),
  KEY `roles_nivel_jerarquia` (`nivel_jerarquia`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `token_blacklist` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `token_hash` varchar(64) NOT NULL,
  `usuario_id` int(11) NOT NULL,
  `expires_at` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `token_hash` (`token_hash`),
  KEY `usuario_id` (`usuario_id`),
  CONSTRAINT `token_blacklist_ibfk_1` FOREIGN KEY (`usuario_id`) REFERENCES `usuarios` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `usuarios` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `email` varchar(100) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `nombre` varchar(75) DEFAULT NULL,
  `apellido` varchar(75) DEFAULT NULL,
  `nombre_completo` varchar(150) DEFAULT NULL,
  `telefono` varchar(20) DEFAULT NULL,
  `cargo` varchar(100) DEFAULT NULL,
  `departamento` varchar(100) DEFAULT 'Operaciones',
  `avatar_url` mediumtext DEFAULT NULL COMMENT 'Avatar como data URI base64 o ruta de archivo',
  `preferencias` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Preferencias del usuario: tema, notificaciones, zona horaria, formato fecha, sesión' CHECK (json_valid(`preferencias`)),
  `rol` varchar(30) DEFAULT 'operador' COMMENT 'Código del rol (legacy, se mantiene por compatibilidad)',
  `rol_id` int(11) DEFAULT NULL COMMENT 'FK a tabla roles (sistema dinámico de roles)',
  `activo` tinyint(1) DEFAULT 1,
  `cliente_id` int(11) DEFAULT NULL COMMENT 'ID del cliente (solo para rol=cliente)',
  `permisos_cliente` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Permisos específicos para usuarios tipo cliente' CHECK (json_valid(`permisos_cliente`)),
  `permisos_personalizados` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Permisos personalizados por usuario (override de rol). Array de permiso_ids o null para usar permisos del rol' CHECK (json_valid(`permisos_personalizados`)),
  `requiere_cambio_password` tinyint(1) DEFAULT 0 COMMENT 'Forzar cambio en primer login',
  `password_expira_en` datetime DEFAULT NULL COMMENT 'Fecha en que vence la contraseña (null = no expira)',
  `invitado_por` int(11) DEFAULT NULL COMMENT 'Usuario que creó la invitación',
  `fecha_invitacion` datetime DEFAULT NULL COMMENT 'Fecha de creación de la cuenta',
  `ultimo_acceso` datetime DEFAULT NULL,
  `reset_token` varchar(255) DEFAULT NULL,
  `reset_token_expires` datetime DEFAULT NULL,
  `intentos_fallidos` int(11) DEFAULT 0,
  `bloqueado_hasta` datetime DEFAULT NULL,
  `totp_secret` varchar(255) DEFAULT NULL COMMENT 'Secreto TOTP base32 para autenticación de dos factores',
  `totp_habilitado` tinyint(1) DEFAULT 0 COMMENT 'Indica si el usuario tiene 2FA activado',
  `totp_backup_codes` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Códigos de respaldo para 2FA (array de strings, one-time use)' CHECK (json_valid(`totp_backup_codes`)),
  `dispositivos_confiables` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Dispositivos de confianza para omitir 2FA. Array de { jti, nombre, creado_en, expira_en }' CHECK (json_valid(`dispositivos_confiables`)),
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `usuarios_username_unique` (`username`),
  UNIQUE KEY `usuarios_email_unique` (`email`),
  KEY `usuarios_email` (`email`),
  KEY `usuarios_username` (`username`),
  KEY `usuarios_rol` (`rol`),
  KEY `usuarios_activo` (`activo`),
  KEY `usuarios_cliente_id` (`cliente_id`),
  KEY `usuarios_rol_cliente_id` (`rol`,`cliente_id`),
  KEY `usuarios_rol_id` (`rol_id`),
  KEY `invitado_por` (`invitado_por`),
  CONSTRAINT `usuarios_ibfk_13` FOREIGN KEY (`rol_id`) REFERENCES `roles` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `usuarios_ibfk_14` FOREIGN KEY (`cliente_id`) REFERENCES `clientes` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `usuarios_ibfk_15` FOREIGN KEY (`invitado_por`) REFERENCES `usuarios` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `vehiculos` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `placa` varchar(10) NOT NULL,
  `tipo_vehiculo` enum('sencillo','tractomula','turbo','dobletroque','minimula','otro') NOT NULL DEFAULT 'sencillo',
  `capacidad_ton` decimal(10,2) DEFAULT 0.00 COMMENT 'Capacidad en toneladas',
  `marca` varchar(50) DEFAULT NULL,
  `modelo` varchar(10) DEFAULT NULL COMMENT 'Año del modelo',
  `color` varchar(30) DEFAULT NULL,
  `vencimiento_soat` date DEFAULT NULL,
  `vencimiento_tecnicomecanica` date DEFAULT NULL,
  `poliza_responsabilidad` varchar(50) DEFAULT NULL,
  `numero_motor` varchar(50) DEFAULT NULL,
  `numero_chasis` varchar(50) DEFAULT NULL,
  `conductor_id` int(11) DEFAULT NULL COMMENT 'Conductor asignado por defecto',
  `descripcion` text DEFAULT NULL,
  `estado` enum('activo','inactivo','mantenimiento') DEFAULT 'activo',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `vehiculos_placa` (`placa`),
  KEY `vehiculos_conductor_id` (`conductor_id`),
  KEY `vehiculos_estado` (`estado`),
  KEY `vehiculos_tipo_vehiculo` (`tipo_vehiculo`),
  KEY `vehiculos_vencimiento_soat` (`vencimiento_soat`),
  KEY `vehiculos_vencimiento_tecnicomecanica` (`vencimiento_tecnicomecanica`),
  CONSTRAINT `vehiculos_ibfk_1` FOREIGN KEY (`conductor_id`) REFERENCES `usuarios` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `viajes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `numero` varchar(20) NOT NULL COMMENT 'Número consecutivo del viaje',
  `fecha` date NOT NULL,
  `vehiculo_id` int(11) NOT NULL,
  `conductor_id` int(11) NOT NULL,
  `caja_menor_id` int(11) DEFAULT NULL COMMENT 'Caja menor asociada (puede ser null si no aplica)',
  `cliente_nombre` varchar(200) DEFAULT NULL COMMENT 'Nombre del cliente destino',
  `documento_cliente` varchar(50) DEFAULT NULL COMMENT 'Documento o remisión del cliente',
  `origen` varchar(100) NOT NULL DEFAULT 'GIRARDOTA',
  `destino` varchar(100) NOT NULL,
  `descripcion` text DEFAULT NULL,
  `peso` decimal(10,2) DEFAULT 0.00 COMMENT 'Peso en kg',
  `valor_descargue` decimal(12,2) DEFAULT 0.00,
  `num_personas` int(11) DEFAULT NULL COMMENT 'Número de personas en el viaje',
  `no_factura` varchar(50) DEFAULT NULL,
  `facturado` tinyint(1) DEFAULT 0,
  `valor_viaje` decimal(12,2) DEFAULT 0.00,
  `estado` enum('activo','completado','anulado') DEFAULT 'activo',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `viajes_numero` (`numero`),
  KEY `viajes_vehiculo_id` (`vehiculo_id`),
  KEY `viajes_conductor_id` (`conductor_id`),
  KEY `viajes_caja_menor_id` (`caja_menor_id`),
  KEY `viajes_fecha` (`fecha`),
  KEY `viajes_estado` (`estado`),
  KEY `viajes_documento_cliente` (`documento_cliente`),
  KEY `viajes_conductor_id_estado` (`conductor_id`,`estado`),
  KEY `viajes_caja_menor_id_estado` (`caja_menor_id`,`estado`),
  KEY `viajes_fecha_estado` (`fecha`,`estado`),
  CONSTRAINT `viajes_ibfk_1` FOREIGN KEY (`vehiculo_id`) REFERENCES `vehiculos` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT `viajes_ibfk_2` FOREIGN KEY (`conductor_id`) REFERENCES `usuarios` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT `viajes_ibfk_3` FOREIGN KEY (`caja_menor_id`) REFERENCES `cajas_menores` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

